### ISSUE TITLE
Make boot-microservice-gui compatible with micro-infra-spring 0.8.4

### ISSUE THREAD

**Issue by szpak** [4finance/boot-microservice-gui#10]
As detected by our [acceptance tests](https://snap-ci.com/4finance/micro-infra-spring/branch/master/logs/defaultPipeline/32/BOOT-GUI-ACCEPTANCE?back_to=build_history) boot-microservice-gui doesn't work with micro-infra-spring 0.8.4.

**Comment by mchmielarz** [comment]
It seems the project is compatible with micro-infra-spring v0.8.7. Checked with [boot-microsevice-gui branch](https://github.com/4finance/boot-microservice/tree/boot-microservice-gui).
