### ISSUE TITLE
Can't access main site of the microservice

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/boot-microservice-gui#3]
Maybe I've done sth wrong but after bumping up micro-infra-spring, when I want to access /index.html I get redirected to Swagger... Check out the branch: https://github.com/4finance/boot-microservice-gui/tree/updatingMicroInfra for an example of such a scenario  (https://github.com/4finance/boot-microservice-gui/commit/b5e41b9581e21d90e69cf0a31f803892fe833342).

**Comment by szpak** [comment]
Is that issue still open with master and should be migrated to boot-microservice?

**Comment by mchmielarz** [comment]
It is still open and will be moved to boot-microservice.

**Comment by szpak** [comment]
Closing as moved to [boot-microservice](https://github.com/4finance/boot-microservice/issues/36).
