### ISSUE TITLE
Duplication with boot-microservice

### ISSUE THREAD

**Issue by szpak** [4finance/boot-microservice-gui#8]
boot-microservice and boot-microservice-gui are very similar. Most of improvements/fixes have to be applied in both plugins. It would be good to be able to keep it in one place, while still provide two versions with and without GUI.

**Comment by szpak** [comment]
In the end it seems that a solution with two branches (+ instruction in README how to checkout selected branch directly) would be the best possible option.

**Comment by mchmielarz** [comment]
Code of this project has been moved to [this branch](https://github.com/4finance/boot-microservice/tree/boot-microservice-gui) in [boot-microservice project](https://github.com/4finance/boot-microservice).
